# ui_part3.py - Statutory Officer Form & Official DGMS Form-VI Register Generator

FORM_UI = """
    <!-- Statutory Officer Form -->
    <div id="vf" class="hidden max-w-lg mx-auto bg-slate-900 border border-slate-800 rounded-2xl p-5 space-y-4">
      <h2 class="font-bold text-base">DGMS Statutory Officer Log Form</h2>
      <form onsubmit="save(event)" class="space-y-3 text-xs">
        <div class="grid grid-cols-2 gap-2">
          <div>
            <label class="text-slate-400 block mb-1">Officer Name</label>
            <input id="soname" required class="w-full bg-slate-800 p-2 rounded-lg text-white" value="Er. Gaurav Yadav">
          </div>
          <div>
            <label class="text-slate-400 block mb-1">Designation / Role</label>
            <input id="sorole" readonly class="w-full bg-slate-800 p-2 rounded-lg text-amber-400 font-semibold" value="Safety Officer (Overman)">
          </div>
        </div>
        <div>
          <label class="text-slate-400 block mb-1">DGMS Certificate / License No.</label>
          <input id="socert" readonly class="w-full bg-slate-800 p-2 rounded-lg text-white font-mono" value="DGMS/CMR/2017/OM-8492">
        </div>
        <div>
          <label class="text-slate-400 block mb-1">Target Mine</label>
          <select id="sm" class="w-full bg-slate-800 p-2 rounded-lg text-white"></select>
        </div>
        <div>
          <label class="text-slate-400 block mb-1">Statutory Regulation Category</label>
          <select id="scat" class="w-full bg-slate-800 p-2 rounded-lg text-white">
            <option>CMR 153: Ventilation & Methane Log</option>
            <option>CMR 106: Bench Stability & Slope</option>
            <option>CMR 169: Daily Blasting & Explosives Log</option>
            <option>CAAQMS: Environmental Dust Standard</option>
          </select>
        </div>
        <div>
          <label class="text-slate-400 block mb-1">Statutory Observation</label>
          <textarea id="sn" required rows="2" class="w-full bg-slate-800 p-2 rounded-lg text-white" placeholder="Hazard or violation detail..."></textarea>
        </div>
        <div class="grid grid-cols-2 gap-2">
          <div>
            <label class="text-slate-400 block mb-1">Severity</label>
            <select id="ss" class="w-full bg-slate-800 p-2 rounded-lg text-white">
              <option value="Normal">Routine (Compliant)</option>
              <option value="Critical">Critical (Immediate Stop Order + Audio Siren)</option>
            </select>
          </div>
          <div>
            <label class="text-slate-400 block mb-1">Lease Boundary Check</label>
            <select id="sgps" class="w-full bg-slate-800 p-2 rounded-lg text-emerald-400">
              <option value="inside">Inside Gevra Lease</option>
              <option value="outside">Outside Lease (Geofence Breach)</option>
            </select>
          </div>
        </div>
        <button type="submit" class="w-full bg-amber-500 hover:bg-amber-400 text-black font-bold p-3 rounded-xl mt-2 transition">Sign & Commit with DSC Seal</button>
      </form>
    </div>
  </main>
"""

def get_form_vi_html(rows):
    return f"""<!DOCTYPE html>
<html>
<head>
    <title>DGMS Form-VI Statutory Inspection Register</title>
    <style>
        body {{ font-family: 'Times New Roman', serif; padding: 25px; color: #111; }}
        .header {{ text-align: center; border-bottom: 2px solid #000; padding-bottom: 10px; margin-bottom: 20px; }}
        table {{ width: 100%; border-collapse: collapse; text-align: left; font-size: 12px; }}
        th {{ border-bottom: 2px solid #000; padding: 8px; background: #f0f0f0; }}
        td {{ border-bottom: 1px solid #ccc; padding: 8px; }}
        .footer {{ margin-top: 40px; display: flex; justify-content: space-between; font-size: 12px; }}
        @media print {{ button {{ display: none; }} }}
    </style>
</head>
<body>
    <div class="header">
        <h2 style="margin: 0;">DIRECTORATE GENERAL OF MINES SAFETY (DGMS)</h2>
        <h3 style="margin: 5px 0;">STATUTORY INSPECTION & BREACH REGISTER (FORM-VI)</h3>
        <p style="margin: 0; font-size: 12px;">Under Coal Mines Regulations (CMR 2017) & Mines Act 1952</p>
    </div>
    <div style="margin-bottom: 15px; text-align: right;">
        <button onclick="window.print()" style="padding: 6px 12px; background: #2563eb; color: white; border: none; border-radius: 4px; cursor: pointer;">Print / Save as PDF</button>
    </div>
    <table>
        <thead>
            <tr>
                <th>Date & Time</th>
                <th>Colliery Name</th>
                <th>Inspecting Officer & DGMS Lic.</th>
                <th>Statutory Category</th>
                <th>Observations & Findings</th>
                <th>Risk Class</th>
                <th>SHA-256 Verification</th>
            </tr>
        </thead>
        <tbody>
            {rows}
        </tbody>
    </table>
    <div class="footer">
        <div>
            <p>Generated by: <strong>MinePulse Statutory AI Engine</strong></p>
            <p>Certified Cryptographically Valid Logbook</p>
        </div>
        <div style="text-align: right;">
            <p>_____________________________________</p>
            <p><strong>Colliery Manager / Safety Officer Signature</strong></p>
            <p>Certified DGMS Competent Person</p>
        </div>
    </div>
</body>
</html>"""
  
