# modules/pdf_engine.py - Statutory Form-VI Vector PDF Generator
from fastapi import APIRouter, Depends, Response
from sqlalchemy.orm import Session
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from io import BytesIO
from datetime import datetime

from database import get_db
from models import Inspection

router = APIRouter(tags=["Statutory Compliance Reports"])

@router.get("/statutory/form-vi/pdf")
def generate_form_vi_pdf(db: Session = Depends(get_db)):
    inspections = db.query(Inspection).order_by(Inspection.id.desc()).all()
    
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=landscape(A4),
        rightMargin=20,
        leftMargin=20,
        topMargin=20,
        bottomMargin=20
    )
    
    elements = []
    styles = getSampleStyleSheet()
    
    # Custom Typography
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=12,
        alignment=1,
        spaceAfter=2
    )
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        alignment=1,
        spaceAfter=10
    )
    cell_style = ParagraphStyle(
        'CellText',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=7,
        leading=9
    )
    cell_bold = ParagraphStyle(
        'CellBold',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=7,
        leading=9
    )

    # Document Header
    elements.append(Paragraph("DIRECTORATE GENERAL OF MINES SAFETY (DGMS)", title_style))
    elements.append(Paragraph("FORM VI - STATUTORY REGISTER OF DAILY SHIFT INSPECTIONS & STATUTORY FINDINGS", title_style))
    elements.append(Paragraph("[Prescribed Under Coal Mines Regulations 2017 - Regulations 27, 106 & 153]", subtitle_style))
    elements.append(Spacer(1, 6))

    # Table Header Row
    data = [[
        Paragraph("Timestamp", cell_bold),
        Paragraph("Colliery / Pit", cell_bold),
        Paragraph("Statutory Officer", cell_bold),
        Paragraph("Cert No.", cell_bold),
        Paragraph("Domain", cell_bold),
        Paragraph("Observations & Orders", cell_bold),
        Paragraph("Severity", cell_bold),
        Paragraph("SHA-256 Seal", cell_bold)
    ]]

    # Data Rows
    for o in inspections:
        ts = str(getattr(o, 'timestamp', ''))[:19]
        mine = str(getattr(o, 'mine_name', 'Gevra Sector B'))
        officer = f"{getattr(o, 'officer_name', '')}\\n({getattr(o, 'officer_role', '')})"
        cert = str(getattr(o, 'dgms_cert_no', ''))
        cat = str(getattr(o, 'category', ''))
        notes = str(getattr(o, 'notes', ''))
        sev = str(getattr(o, 'severity', 'Normal'))
        h = str(getattr(o, 'sha256_hash', 'SEAL'))[:16] + "..."

        sev_color = colors.red if sev.lower() == "critical" else colors.green

        data.append([
            Paragraph(ts, cell_style),
            Paragraph(mine, cell_bold),
            Paragraph(officer, cell_style),
            Paragraph(cert, cell_style),
            Paragraph(cat, cell_style),
            Paragraph(notes, cell_style),
            Paragraph(f"<font color='{sev_color.hexval()}'><b>{sev}</b></font>", cell_style),
            Paragraph(h, cell_style)
        ])

    if len(data) == 1:
        data.append([Paragraph("No statutory inspections recorded.", cell_style)] * 8)

    table = Table(data, colWidths=[70, 95, 105, 75, 120, 200, 55, 80])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#f1f5f9')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#94a3b8')),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]))
    
    elements.append(table)
    elements.append(Spacer(1, 20))
    
    # Signature Footer
    sign_table = Table([
        [
            Paragraph("<b>Generated By:</b> MinePulse Autonomous Core", cell_style),
            Paragraph("<b>Verified By:</b> Safety Officer / Manager", cell_style),
            Paragraph("<b>Statutory Countersign:</b> Agent / General Manager", cell_style)
        ]
    ], colWidths=[250, 250, 250])
    elements.append(sign_table)

    doc.build(elements)
    buffer.seek(0)
    
    filename = f"DGMS_Form_VI_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.pdf"
    return Response(
        content=buffer.getvalue(),
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )
  
